### ISSUE TITLE
Initialization of HACS integration is inactive if the air conditioner is turned on when the Home Assistant is turned on.

### ISSUE THREAD

**Issue by odis68** [RobHofmann/HomeAssistant-GreeClimateComponent#113]
Initialization of HACS integration is inactive if the air conditioner is turned on when the Home Assistant is turned on.

At the same time, the integration of nodered picked up and works with it.
Help how to reinitate your integration after turning on the air conditioner. 
![изображение](https://user-images.githubusercontent.com/46837765/140592591-8ae17893-572a-4f16-b60a-c7d17fabb6f8.png)

thanks

**Comment by 9a4gl** [comment]
I am also having this issue, IMO, integration shall pull every hour and check availability.

**Comment by RobHofmann** [comment]
I think this is due to how HASS works. We might need to switch to config flow instead of yaml configs so you can reload the integration on demand without restart of HASS. Closing this one for now, because I can't fix this without https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/52
