### ISSUE TITLE
Temperature Range 

### ISSUE THREAD

**Issue by hgelpke** [RobHofmann/HomeAssistant-GreeClimateComponent#137]
I had brought up a similar issue a long time ago but it has since been closed

Looking at the integration, everything works fine in terms of operation but the temperatures are off. 

My system units are in Fahrenheit, but the temps in the addon seeming are in Celcius

I looked at the python script and it looks like the temp range is 8-30 which works for Celcius temps but is too low for Fahrenheit.

I'm thinking that may cause the addon to seemingly show the wrong unit when it's actually just constrained to the temp range

**Comment by kspearrin** [comment]
Yes, same issue here. I kind-of fixed it by changing this line:

https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/blob/master/custom_components/gree/climate.py#L131

to this:

```
self._unit_of_measurement = '°C'
```

Now it feeds the correct reading back to HA in Celsius, and lets HA convert it back to Fahrenheit based on its user settings.

The reason I say this kind-of works is there are now problems with adjusting the temperature. I think each up and down step are 1 degrees Celsius instead of Fahrenheit, so it is inconsistent.

**Comment by jgus** [comment]
I'm seeing this too. My system uses Fahrenheit, the Gree android app works in Fahrenheit, and the display on the unit itself is in Fahrenheit. This HA integration, though, works in the Celsius range, even though it's _reporting_ that it's in Fahrenheit too.

**Comment by RobHofmann** [comment]
Feel free to create a PR with support for Fahrenheit. Closing this issue for now.
