### ISSUE TITLE
It doesn't show offline after restart of AC

### ISSUE THREAD

**Issue by NapalmCandy** [RobHofmann/HomeAssistant-GreeClimateComponent#143]
From several time ago, at least 2 years, when I pull off and pull in AC again it will not show online in Home Assistant, it will show online after 2-7 days, no matter what I try to do, reset router,reset AC, reset Homes assistant 

1. Disconnect from electricity the AC unit
2. Connect again,.wait...

**Comment by BartOpitz** [comment]
Good hint. I would also love to get some kind support for taking the device online/offline in HA. It takes 10-80W when turned off, and since I use it very rare, I have a smart plug that cuts power off. I might consider running an automation, that when all AC units are in off mode, after 10 minutes cuts power. But then there is this issue of re-connecting and it would be ideal, that when I want to turn AC on from the climate controller this would activate my smart plug to power it on, wait until it reaches wifi/responds to requests and only then send proper request. this could save a LOT of electricity...

**Comment by RobHofmann** [comment]
This would mean we have to switch to config_flow instead of YAML configuration. Then you would be able to reload the component from the UI. This is currently a limitation of HASS.

This is the issue you are looking for: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/52

Closing this one for now.
