### ISSUE TITLE
toggle on off command

### ISSUE THREAD

**Issue by KarelsonPL** [RobHofmann/HomeAssistant-GreeClimateComponent#37]
When I integrate the code to Home assistant the options to turn on and off are:

1. on - need to choose auto,cool,dry,fan_only,heat.
2.off - need to choose off.

I would like only to toggle between on and off. while on is the last state the AC was on.

The reason I want it, is to configure on a smart switch one button that each press will togle the AC to ON and OFF. that way I can turn ON/OFF in a pres of a button like a light.  using an automation similar to light see below.

- alias: 'Toggle Philips light on single press from sonoff6 2CH'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.Kitchen_corner_SW_Kids ----------> this would be the smart switch button
   ! # to: ANYSTATE WAS CHANGE (ON/OFF)
  action:
    service: switch.toggle ----------> this would be the AC
    entity_id: switch.Kids ----------> this would be the AC

Hope you can help.

Thank you.

**Comment by RobHofmann** [comment]
As far as I know, this is not possible. This is due to the climate platform changes in Home Assistant. In an older version of this component (not compatible with the current home assistant version), it used to work like you described.

I'm afraid you will have to write your own system for this. Maybe something with a template switch? I'd ask this question on the home assistant forums.

Feel free to reopen this issue if you think my information is incorrect.
