### ISSUE TITLE
Homekit scene sends command that HA can't recognize

### ISSUE THREAD

**Issue by zaberxxx** [RobHofmann/HomeAssistant-GreeClimateComponent#97]
**Describe the bug**
Hi, thank you for developing this Gree HVAC add-on for Home Assistant. It's great in every aspect in home assistant, however, I experiencing some glitch when setting up the Gree AC as part of a scene in HomeKit. eg. if I set a scene that includes Gree AC to lower the temperature to 18'C, the HomeKit Gree tile will show cooling to 18'C BUT the AC itself won't wake up from "off" to "cool" mode. I suppose it's because it's using "command.set_temperature" to set HVAC mode instead of "command.set_hvac_mode".

![IMG_1486](https://user-images.githubusercontent.com/73158577/115098759-6087f180-9f64-11eb-9c40-dc382340f951.jpeg)

**Comment by RobHofmann** [comment]
Personally I use scripts instead of scenes. This does work for me in HomeKit.

**Comment by zaberxxx** [comment]
> Personally I use scripts instead of scenes. This does work for me in HomeKit.

Sorry, I didn't make myself clear. I mean the scene created in Home App.

**Comment by santiacho** [comment]
why was this closed?

**Comment by RobHofmann** [comment]
Lack of activity in the past 3 years :).

Feel free to create a PR with a fix for this.

**Comment by santiacho** [comment]
I'm not sure I know how to fix it. 
I got this from the Homekit automation (11:19:05) and the device itself (11:19:55)when turning it off from Homkit.
The automation is set to turn off the heating/cooling machine, but the command received by the Home Assistant is set_temperature instead of set_hvac_mode 🤔

![Screenshot 2024-09-11 at 13 43 30](https://github.com/user-attachments/assets/1a27e884-99b1-4494-8891-b2ebbe6a02d9)
